language: android
dist: trusty

android:
  components:
    - build-tools-29.0.2
    - android-28
    - android-29

script:
  - ./gradlew clean check assemble -Dpre-dex=false

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle